### ISSUE TITLE
About Python version

### ISSUE THREAD

**Issue by dk-kim** [weijianan1/NVI#2]
Thank you for interesting work!
I want to reproduce your work but I have trouble in setting environments. 
Packages are conflicted, and cannot install required packages. 
Could you specify the python version and check again you requirements.txt file?

**Comment by dk-kim** [comment]
<img width="1541" alt="스크린샷 2024-10-29 오후 2 44 05" src="https://github.com/user-attachments/assets/5c066fa8-e4f2-4d7e-803f-7bf424175103">

I see that you have modified the installation instruction, but it still does not work for me. 
Python 3.9 is compatible with my setup.

**Comment by weijianan1** [comment]
Looks like salesforce_lavis doesn't set a version limit for spacy, and the latest spacy needs Python 3.9+. So, before installing salesforce_lavis, make sure to install spacy <=3.8.2.

**Comment by dk-kim** [comment]
<img width="752" alt="스크린샷 2024-10-29 오후 5 07 31" src="https://github.com/user-attachments/assets/a4c8f73f-b820-412b-a202-27895c6e4666">

There are still issues (conflict between scikit-image and numpy 1.20.0, and incompatibility between peft and PyTorch 1.12.1), but training is progressing, and I'm checking on it. Thanks for the help.
